version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hyper
    versions:
    - ">= 0.11.a, < 0.12"
  - dependency-name: hyper
    versions:
    - ">= 0.12.a, < 0.13"
  - dependency-name: hyper
    versions:
    - ">= 0.13.a, < 0.14"
  - dependency-name: hyper
    versions:
    - ">= 0.14.a, < 0.15"
